name: build

'on':
  push:
    branches:
      - base

  pull_request:
    branches:
      - base

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
